version: '3.8'
services:
  dev:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      APP_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
